#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrdb merge .Xresources
xss-lock -- lock &

picom &
~/.config/polybar/launch.sh &
~/.fehbg &

dunst -config ~/.config/dunst/dunstrc &
nmcli connection up Barsik_2
pamixer -u &
numlockx &
xfce4-power-manager &


# Config
bspc monitor -d I II III IV V

bspc config border_width            2
bspc config window_gap              20

bspc config top_padding             40
bspc config right_padding           20
bspc config bottom_padding          10
bspc config left_padding            20

bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focused_border_color "#d79920"
# bspc config normal_border_color "#"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a TelegramDesktop desktop='^4'
