#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrdb merge .Xresources
xss-lock -- lock &

picom &
~/.config/polybar/launch.sh &
~/.fehbg &

dunst -config ~/.config/dunst/dunstrc &
nmcli connection up Barsik_2
pamixer -u &
numlockx &
xfce4-power-manager &

# Config
bspc monitor -d I II III IV V

bspc config border_width            1
bspc config window_gap              30

bspc config top_padding             50
bspc config right_padding           30
bspc config bottom_padding          20
bspc config left_padding            30

bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focused_border_color "#a89983"
bspc config normal_border_color "#272727"

bspc rule -a brave desktop='^1'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Thunderbird desktop='^5'
bspc rule -a SpeedCrunch state=floating
